---
title: "ELS Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
```

ELS Data needs to be downloaded from:

https://nces.ed.gov/EDAT/Data/Zip/ELS_2002-12_PETS_v1_0_Student_R_Datasets.zip

The zip file needs to opened up in your working directory so the code below will work. 

```{r}
# Load R Data File
if(file.exists("els.Rdata")==FALSE){
load("els_02_12_byf3pststu_v1_0.rdata")
els<-els_02_12_byf3pststu_v1_0
rm(els_02_12_byf3pststu_v1_0)

names(els)<-tolower(names(els))

# Create vector of selected variables
keepvars <- tolower(c(
   "stu_id", ## Student ID
   "sch_id", ## School ID
   "strat_id", ## Stratum ID
   "psu", ## Primary sampling unit
   "BYRACE", ##  Race
   "BYSES1", ## SEs
   "BYINCOME", ## Income
   "BYPARED", ## Parental Education
   "BYNELS2M", ## Math Score
   "BYNELS2R", ## Reading Score
   "F3ATTAINMENT", ## Atainment
   "F2PS1SEC" ##First inst attended
   ))

els%>%
   select(one_of(keepvars))->els

save(els,file="els.Rds")
} else {
load("els.rds")
}
```

```{r}

## recode all less than -3 as missing
els<-els%>%mutate_all( ~ifelse(.x< (-3), ## Logical test
                               NA, ## Value if true
                               .x) ## value if false
                       )

## OR ##
els<-els%>%
   mutate_all( ~ifelse(.x %in% c(-4,-8,-9), ## Logical test
                      NA, ## value if true
                      .x) ## Value if false
               )

## Only people who started at four years

els<-els%>%filter(f2ps1sec%in%c(1:3))

## create variable for completing a ba

els<-els%>%mutate(ba_complete=ifelse(
                                    f3attainment%in%c(6,7,8,10), ## Test
                                     1, ## Value if true
                                     0) ## Value if false
                  )

## average bachelor's completion overall

els%>%summarize(mean(ba_complete))

## 62.1 percent of those who started at a 4 year had a degree within 8 years. 

```

